/*
 * lightway-expresslane-cffi: C ABI for ExpressLane data-packet
 * encrypt/decrypt primitives (lightway-expresslane).
 *
 * This header is auto-generated by cbindgen. DO NOT EDIT BY HAND.
 */


#ifndef XV_LIGHTWAY_EXPRESSLANE_CFFI_H
#define XV_LIGHTWAY_EXPRESSLANE_CFFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/*
 Return codes used by all `he_expresslane_*` functions.
 */
typedef enum {
    /*
     Operation succeeded.
     */
    HE_EXPRESSLANE_SUCCESS = 0,
    /*
     A null pointer was supplied where one is not permitted.
     */
    HE_EXPRESSLANE_ERR_NULL_POINTER = -1,
    /*
     Caller-provided output buffer is too small.
     */
    HE_EXPRESSLANE_ERR_BUFFER_TOO_SMALL = -2,
    /*
     Wire packet is shorter than the minimum ExpressLane header.
     */
    HE_EXPRESSLANE_ERR_INSUFFICIENT_DATA = -3,
    /*
     AEAD authentication failed, or the packet is otherwise malformed.
     */
    HE_EXPRESSLANE_ERR_INVALID_DATA = -4,
    /*
     Wire counter was rejected by the replay window.
     */
    HE_EXPRESSLANE_ERR_REPLAYED = -5,
    /*
     No key is installed for this operation.
     */
    HE_EXPRESSLANE_ERR_KEY_NOT_SET = -6,
    /*
     Key material could not be loaded into the cipher.
     */
    HE_EXPRESSLANE_ERR_INVALID_KEY = -7,
    /*
     A panic was caught at the FFI boundary.
     */
    HE_EXPRESSLANE_ERR_PANIC = -8,
} he_expresslane_return_code_t;

/*
 ExpressLane wire-format version, matching `lightway_expresslane::ExpresslaneVersion`.

 `he_expresslane_session_create` takes a raw `uint8_t` rather than this
 enum type directly, so these constants are provided for callers to use
 by name; cbindgen forces their emission via `cbindgen.toml`'s
 `[export] include`.
 */
enum he_expresslane_version_t
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    /*
     Not yet negotiated / not recognised by this build.
     */
    HE_EXPRESSLANE_VERSION_UNKNOWN = 0,
    /*
     Initial ExpressLane wire format.
     */
    HE_EXPRESSLANE_VERSION_1 = 1,
    /*
     Full 16-bit flags field bound into the AEAD AAD.
     */
    HE_EXPRESSLANE_VERSION_2 = 2,
};
#ifndef __cplusplus
typedef uint8_t he_expresslane_version_t;
#endif // __cplusplus

/*
 Opaque ExpressLane packet-crypto session handle.
 */
typedef struct he_expresslane_session_t he_expresslane_session_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Allocate a new ExpressLane session for the given wire version.

 `version` is a raw byte (1 = V1, 2 = V2 — see `he_expresslane_version_t`).
 The version selects the AEAD AAD layout (V2 binds the flags field, V1 does
 not), so an unrecognized value — including 0
 (`HE_EXPRESSLANE_VERSION_UNKNOWN`) — returns **NULL** rather than silently
 running in V1 mode, which against a peer that negotiated the other version
 would make every packet fail authentication with no distinguishing error.

 Returns a heap-allocated pointer, or NULL for an unrecognized version.
 (Allocation failure does not return NULL — Rust's default global allocator
 aborts the process on OOM, which `ffi_guard` cannot intercept.) The caller
 must free a non-NULL result with `he_expresslane_session_destroy`.

 # Safety
 The returned pointer must be freed with `he_expresslane_session_destroy`.
 */
he_expresslane_session_t *he_expresslane_session_create(uint8_t version);

/*
 Free a session previously allocated by `he_expresslane_session_create`.

 # Safety
 `session` must be a valid pointer obtained from
 `he_expresslane_session_create` and must not be used after this call.
 The caller must ensure no other thread is calling any
 `he_expresslane_*` function on this handle concurrently with (or after)
 destruction.
 */
void he_expresslane_session_destroy(he_expresslane_session_t *session);

/*
 Reserve a wire counter value for this session — unique per call until the
 internal 64-bit counter wraps (after 2^64 reservations; unreachable in
 practice). Safe to call concurrently from multiple threads on the same
 session. Returns 0 if `session` is null; a live session returns 1, 2, 3, …
 (0 recurs only after the astronomically distant wrap).

 # Safety
 `session` must be a valid non-null pointer or null.
 */
uint64_t he_expresslane_reserve_counter(const he_expresslane_session_t *session);

/*
 Stage a new "next self" key. Call `he_expresslane_promote_self_key` once
 the peer has acknowledged the rotation to make it the active send key.
 Safe to call concurrently with `he_expresslane_encrypt` on the same
 session. Returns `HE_EXPRESSLANE_ERR_INVALID_KEY` for an all-zero key.

 # Safety
 `session` must be a valid non-null pointer. `key` must point to 32
 readable bytes.
 */
he_expresslane_return_code_t he_expresslane_set_next_self_key(const he_expresslane_session_t *session,
                                                              const uint8_t *key);

/*
 Promote the staged "next self" key to the active send key. A no-op if
 no key is staged. Safe to call concurrently with `he_expresslane_encrypt`
 on the same session.

 # Safety
 `session` must be a valid non-null pointer or null.
 */
void he_expresslane_promote_self_key(const he_expresslane_session_t *session);

/*
 Total number of packets successfully encrypted so far on this session.

 # Safety
 `session` must be a valid non-null pointer or null.
 */
uint64_t he_expresslane_packets_sent(const he_expresslane_session_t *session);

/*
 Encrypt `plain_text` into ExpressLane wire format. Safe to call
 concurrently from multiple threads on the same session, provided each call
 uses a unique `counter` (see `he_expresslane_reserve_counter`) AND a unique
 `iv` — see the IV section below; a unique `counter` does not make the `iv`
 unique.

 `out` must have capacity for at least
 `he_expresslane_wire_overhead() + plain_text_len` bytes. On success,
 `*out_len` is set to the number of bytes written to `out`.

 # IV / nonce uniqueness (SECURITY-CRITICAL)
 `iv` is the AES-GCM nonce. The caller MUST supply a UNIQUE 12-byte `iv`
 for every packet encrypted under a given key — either a deterministic
 construction that cannot repeat (e.g. derived from a per-key message
 counter) or random generation from a CSPRNG when no such guarantee
 exists. Predictability is not the concern; repetition is: reusing a
 `(key, iv)` pair is catastrophic for AES-GCM — it leaks the XOR of the
 plaintexts and enables forgery of arbitrary packets. The `counter`
 argument is authenticated but is NOT the nonce; a unique `counter` does
 not make the `iv` unique. This library has no RNG and cannot enforce this.

 # Safety
 `session` must be a valid non-null pointer. `session_id` must point to 8
 readable bytes. `plain_text` must point to `plain_text_len` readable
 bytes (it may be NULL when `plain_text_len` is 0 — the conventional C
 idiom for an empty payload). `iv` must point to 12 readable bytes. `out`
 must point to `out_capacity` writable bytes and must NOT overlap any of
 the input buffers. `out_len` must be a valid pointer to a `uintptr_t`
 (the C type cbindgen emits for the Rust `usize` length parameters).
 */
he_expresslane_return_code_t he_expresslane_encrypt(const he_expresslane_session_t *session,
                                                    uint64_t counter,
                                                    const uint8_t *session_id,
                                                    const uint8_t *plain_text,
                                                    uintptr_t plain_text_len,
                                                    const uint8_t *iv,
                                                    bool is_encoded,
                                                    uint8_t *out,
                                                    uintptr_t out_capacity,
                                                    uintptr_t *out_len);

/*
 Install a new peer (receive) key. The previous peer key becomes the
 fallback used by `he_expresslane_decrypt` for packets still in flight
 from before the peer's rotation. Returns
 `HE_EXPRESSLANE_ERR_INVALID_KEY` for an all-zero key.

 The lock-taking receive-side calls (`he_expresslane_decrypt`, this
 function, `he_expresslane_packets_received`) are serialized internally per
 session, so this is safe to call from any thread; concurrent RX calls simply
 take turns. `he_expresslane_has_valid_keys` is deliberately not among them —
 it is lock-free and never waits on this one.

 # Safety
 `session` must be a valid non-null pointer. `key` must point to 32
 readable bytes.
 */
he_expresslane_return_code_t he_expresslane_set_peer_key(const he_expresslane_session_t *session,
                                                         const uint8_t *key);

/*
 True if both a self (send) key and a peer (receive) key are installed.

 Lock-free: a pair of relaxed atomic loads, taking neither the receive-side
 mutex nor the send-side lock. Safe to call from any thread, and in
 particular safe to call per outbound packet without contending with an
 in-progress inbound `he_expresslane_decrypt`.

 The answer is a hint, not a synchronized snapshot: because it takes no lock,
 a caller on another thread may see `false` for a moment after a key really
 is installed. It never goes back to `false` once it has read `true`. Treat
 `false` as "not yet, retry", never as "key delivery failed" —
 `he_expresslane_encrypt` / `he_expresslane_decrypt` re-check under their own
 locks and return `HE_EXPRESSLANE_ERR_KEY_NOT_SET` if a key really is missing.

 # Safety
 `session` must be a valid non-null pointer or null.
 */
bool he_expresslane_has_valid_keys(const he_expresslane_session_t *session);

/*
 Total number of packets successfully decrypted so far on this session.
 Serialized internally with the other receive-side calls, so safe to call
 from any thread.

 # Safety
 `session` must be a valid non-null pointer or null.
 */
uint64_t he_expresslane_packets_received(const he_expresslane_session_t *session);

/*
 Decrypt `wire_packet` (ExpressLane wire format) into `out`. `out` must
 have capacity for at least `wire_packet_len - he_expresslane_wire_overhead()`
 bytes. On success, `*out_len` is set to the plaintext length and
 `*is_encoded` to the packet's encoded flag. The lock-taking receive-side
 calls (`he_expresslane_set_peer_key`, `he_expresslane_packets_received` and
 this one) are serialized internally per session, so this is safe to call
 from any thread. `he_expresslane_has_valid_keys` is deliberately not among
 them: it is lock-free, so a sender polling it per outbound packet does not
 wait on an in-progress decrypt.

 # Safety
 `session` must be a valid non-null pointer. `session_id` must point to 8
 readable bytes. `wire_packet` must point to `wire_packet_len` readable
 bytes. `out` must point to `out_capacity` writable bytes (it may be NULL
 when `out_capacity` is 0, e.g. for a packet known to carry an empty
 payload) and must NOT overlap `wire_packet`. `out_len` and `is_encoded`
 must be valid pointers.
 */
he_expresslane_return_code_t he_expresslane_decrypt(const he_expresslane_session_t *session,
                                                    const uint8_t *session_id,
                                                    const uint8_t *wire_packet,
                                                    uintptr_t wire_packet_len,
                                                    uint8_t *out,
                                                    uintptr_t out_capacity,
                                                    uintptr_t *out_len,
                                                    bool *is_encoded);

/*
 Wire overhead in bytes (40): counter(8) + iv(12) + tag(16) + data_len(2)
 + flags(2).

 Use this to size buffers for `he_expresslane_encrypt` /
 `he_expresslane_decrypt` without hardcoding the constant.
 */
uintptr_t he_expresslane_wire_overhead(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XV_LIGHTWAY_EXPRESSLANE_CFFI_H */
