/*
 * lightway-expresslane-cffi: C ABI for ExpressLane data-packet
 * encrypt/decrypt primitives (lightway-expresslane, pure Rust).
 *
 * This header is auto-generated by cbindgen. DO NOT EDIT BY HAND.
 */


#ifndef XV_LIGHTWAY_EXPRESSLANE_CFFI_H
#define XV_LIGHTWAY_EXPRESSLANE_CFFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/*
 ExpressLane wire-format version, matching `lightway_expresslane::ExpresslaneVersion`.

 `he_expresslane_session_create` takes a raw `uint8_t` rather than this
 enum type directly, so these constants are provided for callers to use
 by name; cbindgen forces their emission via `cbindgen.toml`'s
 `[export] include`.
 */
enum he_expresslane_version_t
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    /*
     Not yet negotiated / not recognised by this build.
     */
    HE_EXPRESSLANE_VERSION_UNKNOWN = 0,
    /*
     Initial ExpressLane wire format.
     */
    HE_EXPRESSLANE_VERSION_1 = 1,
    /*
     Flags byte bound into the AEAD AAD.
     */
    HE_EXPRESSLANE_VERSION_2 = 2,
};
#ifndef __cplusplus
typedef uint8_t he_expresslane_version_t;
#endif // __cplusplus

/*
 Opaque ExpressLane packet-crypto session handle.
 */
typedef struct he_expresslane_session_t he_expresslane_session_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Allocate a new ExpressLane session for the given wire version.

 `version` is a raw byte (0 = unknown, 1 = V1, 2 = V2 — see
 `he_expresslane_version_t`) rather than the enum type directly, so an
 out-of-range value from C falls back to `HE_EXPRESSLANE_VERSION_UNKNOWN`
 instead of being reinterpreted as an invalid discriminant.

 Returns a heap-allocated pointer. The caller must free it with
 `he_expresslane_session_destroy`.

 # Safety
 The returned pointer must be freed with `he_expresslane_session_destroy`.
 */
he_expresslane_session_t *he_expresslane_session_create(uint8_t version);

/*
 Free a session previously allocated by `he_expresslane_session_create`.

 # Safety
 `session` must be a valid pointer obtained from
 `he_expresslane_session_create` and must not be used after this call.
 The caller must ensure no other thread is calling any
 `he_expresslane_*` function on this handle concurrently with (or after)
 destruction.
 */
void he_expresslane_session_destroy(he_expresslane_session_t *session);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XV_LIGHTWAY_EXPRESSLANE_CFFI_H */
