/*
 * lightway-expresslane-cffi: C ABI for ExpressLane data-packet
 * encrypt/decrypt primitives (lightway-expresslane, pure Rust).
 *
 * This header is auto-generated by cbindgen. DO NOT EDIT BY HAND.
 */


#ifndef XV_LIGHTWAY_EXPRESSLANE_CFFI_H
#define XV_LIGHTWAY_EXPRESSLANE_CFFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/*
 Return codes used by all `he_expresslane_*` functions.
 */
typedef enum {
    /*
     Operation succeeded.
     */
    HE_EXPRESSLANE_SUCCESS = 0,
    /*
     A null pointer was supplied where one is not permitted.
     */
    HE_EXPRESSLANE_ERR_NULL_POINTER = -1,
    /*
     Caller-provided output buffer is too small.
     */
    HE_EXPRESSLANE_ERR_BUFFER_TOO_SMALL = -2,
    /*
     Wire packet is shorter than the minimum ExpressLane header.
     */
    HE_EXPRESSLANE_ERR_INSUFFICIENT_DATA = -3,
    /*
     AEAD authentication failed, or the packet is otherwise malformed.
     */
    HE_EXPRESSLANE_ERR_INVALID_DATA = -4,
    /*
     Wire counter was rejected by the replay window.
     */
    HE_EXPRESSLANE_ERR_REPLAYED = -5,
    /*
     No key is installed for this operation.
     */
    HE_EXPRESSLANE_ERR_KEY_NOT_SET = -6,
    /*
     Key material could not be loaded into the cipher.
     */
    HE_EXPRESSLANE_ERR_INVALID_KEY = -7,
    /*
     A panic was caught at the FFI boundary.
     */
    HE_EXPRESSLANE_ERR_PANIC = -8,
} he_expresslane_return_code_t;

/*
 ExpressLane wire-format version, matching `lightway_expresslane::ExpresslaneVersion`.

 `he_expresslane_session_create` takes a raw `uint8_t` rather than this
 enum type directly, so these constants are provided for callers to use
 by name; cbindgen forces their emission via `cbindgen.toml`'s
 `[export] include`.
 */
enum he_expresslane_version_t
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    /*
     Not yet negotiated / not recognised by this build.
     */
    HE_EXPRESSLANE_VERSION_UNKNOWN = 0,
    /*
     Initial ExpressLane wire format.
     */
    HE_EXPRESSLANE_VERSION_1 = 1,
    /*
     Flags byte bound into the AEAD AAD.
     */
    HE_EXPRESSLANE_VERSION_2 = 2,
};
#ifndef __cplusplus
typedef uint8_t he_expresslane_version_t;
#endif // __cplusplus

/*
 Opaque ExpressLane packet-crypto session handle.
 */
typedef struct he_expresslane_session_t he_expresslane_session_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Allocate a new ExpressLane session for the given wire version.

 `version` is a raw byte (0 = unknown, 1 = V1, 2 = V2 — see
 `he_expresslane_version_t`) rather than the enum type directly, so an
 out-of-range value from C falls back to `HE_EXPRESSLANE_VERSION_UNKNOWN`
 instead of being reinterpreted as an invalid discriminant.

 Returns a heap-allocated pointer. The caller must free it with
 `he_expresslane_session_destroy`.

 # Safety
 The returned pointer must be freed with `he_expresslane_session_destroy`.
 */
he_expresslane_session_t *he_expresslane_session_create(uint8_t version);

/*
 Free a session previously allocated by `he_expresslane_session_create`.

 # Safety
 `session` must be a valid pointer obtained from
 `he_expresslane_session_create` and must not be used after this call.
 The caller must ensure no other thread is calling any
 `he_expresslane_*` function on this handle concurrently with (or after)
 destruction.
 */
void he_expresslane_session_destroy(he_expresslane_session_t *session);

/*
 Reserve a wire counter value guaranteed unique for this session. Safe to
 call concurrently from multiple threads on the same session. Returns 0
 if `session` is null (0 is never a value `reserve_counter` itself would
 return, since it starts at 1).

 # Safety
 `session` must be a valid non-null pointer or null.
 */
uint64_t he_expresslane_reserve_counter(const he_expresslane_session_t *session);

/*
 Stage a new "next self" key. Call `he_expresslane_promote_self_key` once
 the peer has acknowledged the rotation to make it the active send key.
 Safe to call concurrently with `he_expresslane_encrypt` on the same
 session.

 # Safety
 `session` must be a valid non-null pointer. `key` must point to 32
 readable bytes.
 */
he_expresslane_return_code_t he_expresslane_set_next_self_key(const he_expresslane_session_t *session,
                                                              const uint8_t *key);

/*
 Promote the staged "next self" key to the active send key. A no-op if
 no key is staged. Safe to call concurrently with `he_expresslane_encrypt`
 on the same session.

 # Safety
 `session` must be a valid non-null pointer or null.
 */
void he_expresslane_promote_self_key(const he_expresslane_session_t *session);

/*
 Total number of packets successfully encrypted so far on this session.

 # Safety
 `session` must be a valid non-null pointer or null.
 */
uint64_t he_expresslane_packets_sent(const he_expresslane_session_t *session);

/*
 Encrypt `plain_text` into ExpressLane wire format. Safe to call
 concurrently from multiple threads on the same session, provided each
 call uses a unique `counter` (see `he_expresslane_reserve_counter`).

 `out` must have capacity for at least
 `he_expresslane_wire_overhead() + plain_text_len` bytes. On success,
 `*out_len` is set to the number of bytes written to `out`.

 # Safety
 `session` must be a valid non-null pointer. `session_id` must point to 8
 readable bytes. `plain_text` must point to `plain_text_len` readable
 bytes. `iv` must point to 12 readable bytes. `out` must point to
 `out_capacity` writable bytes. `out_len` must be a valid pointer to a
 `size_t`.
 */
he_expresslane_return_code_t he_expresslane_encrypt(const he_expresslane_session_t *session,
                                                    uint64_t counter,
                                                    const uint8_t *session_id,
                                                    const uint8_t *plain_text,
                                                    uintptr_t plain_text_len,
                                                    const uint8_t *iv,
                                                    bool is_encoded,
                                                    uint8_t *out,
                                                    uintptr_t out_capacity,
                                                    uintptr_t *out_len);

/*
 Install a new peer (receive) key. The previous peer key becomes the
 fallback used by `he_expresslane_decrypt` for packets still in flight
 from before the peer's rotation. Caller must externally serialize this
 call against `he_expresslane_decrypt`/`he_expresslane_has_valid_keys`/
 `he_expresslane_packets_received` on the same session.

 # Safety
 `session` must be a valid non-null pointer. `key` must point to 32
 readable bytes.
 */
he_expresslane_return_code_t he_expresslane_set_peer_key(he_expresslane_session_t *session,
                                                         const uint8_t *key);

/*
 True if both a self (send) key and a peer (receive) key are installed.
 Caller must externally serialize this call against
 `he_expresslane_decrypt`/`he_expresslane_set_peer_key` on the same
 session.

 # Safety
 `session` must be a valid non-null pointer.
 */
bool he_expresslane_has_valid_keys(he_expresslane_session_t *session);

/*
 Total number of packets successfully decrypted so far on this session.
 Caller must externally serialize this call against
 `he_expresslane_decrypt` on the same session.

 # Safety
 `session` must be a valid non-null pointer or null.
 */
uint64_t he_expresslane_packets_received(he_expresslane_session_t *session);

/*
 Decrypt `wire_packet` (ExpressLane wire format) into `out`. `out` must
 have capacity for at least `wire_packet_len - he_expresslane_wire_overhead()`
 bytes. On success, `*out_len` is set to the plaintext length and
 `*is_encoded` to the packet's encoded flag. Caller must externally
 serialize this call against `he_expresslane_set_peer_key`/
 `he_expresslane_has_valid_keys`/`he_expresslane_packets_received` on the
 same session — no internal locking.

 # Safety
 `session` must be a valid non-null pointer. `session_id` must point to 8
 readable bytes. `wire_packet` must point to `wire_packet_len` readable
 bytes. `out` must point to `out_capacity` writable bytes. `out_len` and
 `is_encoded` must be valid pointers.
 */
he_expresslane_return_code_t he_expresslane_decrypt(he_expresslane_session_t *session,
                                                    const uint8_t *session_id,
                                                    const uint8_t *wire_packet,
                                                    uintptr_t wire_packet_len,
                                                    uint8_t *out,
                                                    uintptr_t out_capacity,
                                                    uintptr_t *out_len,
                                                    bool *is_encoded);

/*
 Wire overhead in bytes (40): counter(8) + iv(12) + tag(16) + data_len(2)
 + flags(2).

 Use this to size buffers for `he_expresslane_encrypt` /
 `he_expresslane_decrypt` without hardcoding the constant.
 */
uintptr_t he_expresslane_wire_overhead(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XV_LIGHTWAY_EXPRESSLANE_CFFI_H */
