/*
 * lightway-cffi: C ABI for lightway-core (Rust).
 *
 * This header is auto-generated by cbindgen. DO NOT EDIT BY HAND.
 *
 * Naming convention (`he_*` / `HE_*`) intentionally mirrors the OSS
 * `expressvpn/lightway-core` C library to keep consumers source-compatible.
 */


#ifndef XV_LIGHTWAY_CFFI_H
#define XV_LIGHTWAY_CFFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
/* he_packet_filter_t and he_domain_filter_t are defined in the C
 * threat-manager library. Include it here so those types are in scope
 * before the function declarations below reference them.
 * The relative path matches the layout used by kp_pkf_client. */
#ifndef XV_LIGHTWAY_CFFI_NO_PACKET_FILTER_INCLUDE
#include "../common/threat-manager/packet_filter.h"
#endif


/*
 Return codes used by all `he_*` functions.

 Values mirror those in the OSS `lightway-core` C library so that existing
 `if (result != HE_SUCCESS)` guards continue to work unchanged.
 */
typedef enum {
    /*
     Operation succeeded.
     */
    HE_SUCCESS = 0,
    /*
     Generic failure.
     */
    HE_ERR_FAILED = -1,
    /*
     A null pointer was supplied where one is not permitted.
     */
    HE_ERR_NULL_POINTER = -2,
    /*
     Memory allocation failed.
     */
    HE_ERR_NO_MEMORY = -3,
    /*
     Buffer too small.
     */
    HE_ERR_BUFFER_TOO_SMALL = -4,
    /*
     Bad parameter value.
     */
    HE_ERR_BAD_PARAM = -5,
    /*
     Server rejected credentials.
     */
    HE_ERR_ACCESS_DENIED = -6,
    /*
     Payload too large.
     */
    HE_ERR_PAYLOAD_TOO_LARGE = -7,
    /*
     String was not NUL-terminated or too long.
     */
    HE_ERR_STRING_TOO_LONG = -8,
    /*
     Connection timed out (used as a non-fatal nudge sentinel).
     */
    HE_CONNECTION_TIMED_OUT = -9,
    /*
     An incorrect protocol version was received.
     */
    HE_ERR_INCORRECT_PROTOCOL_VERSION = -10,
    /*
     SSL / crypto error.
     */
    HE_ERR_SSL_ERROR = -11,
    /*
     Configuration is not yet complete.
     */
    HE_ERR_CONF_NOT_SET = -12,
    /*
     The operation was called at the wrong connection state.
     */
    HE_ERR_INVALID_CONN_STATE = -13,
} he_return_code_t;

/*
 Lightway connection state, delivered to `he_state_change_cb_t`.
 */
typedef enum {
    /*
     Initial / unset state.
     */
    HE_STATE_NONE = 0,
    /*
     Fully disconnected.
     */
    HE_STATE_DISCONNECTED = 1,
    /*
     Performing TLS handshake.
     */
    HE_STATE_CONNECTING = 2,
    /*
     Graceful disconnect in progress.
     */
    HE_STATE_DISCONNECTING = 3,
    /*
     Authenticating with the server.
     */
    HE_STATE_AUTHENTICATING = 4,
    /*
     Link layer is up (pre-IP config).
     */
    HE_STATE_LINK_UP = 5,
    /*
     Receiving IP configuration from server.
     */
    HE_STATE_CONFIGURING = 6,
    /*
     Fully online — data traffic flowing.
     */
    HE_STATE_ONLINE = 7,
} he_conn_state_t;

/*
 Asynchronous events delivered to `he_event_cb_t`.
 */
typedef enum {
    /*
     First message received from server.
     */
    HE_EVENT_FIRST_MESSAGE_RECEIVED = 1,
    /*
     Keepalive pong received.
     */
    HE_EVENT_PONG = 2,
    /*
     Server rejected fragmented packets from host.
     */
    HE_EVENT_REJECTED_FRAGMENTED_PACKETS_SENT_BY_HOST = 3,
    /*
     Secure renegotiation started.
     */
    HE_EVENT_SECURE_RENEGOTIATION_STARTED = 4,
    /*
     Secure renegotiation completed.
     */
    HE_EVENT_SECURE_RENEGOTIATION_COMPLETED = 5,
    /*
     Pending session acknowledged.
     */
    HE_EVENT_PENDING_SESSION_ACKNOWLEDGED = 6,
} he_conn_event_t;

/*
 Path MTU Discovery state delivered to `he_pmtud_state_change_cb_t`.
 */
typedef enum {
    /*
     Base / initial state.
     */
    HE_PMTUD_STATE_BASE = 0,
    /*
     Discovery disabled.
     */
    HE_PMTUD_STATE_DISABLED = 1,
    /*
     Probing in progress.
     */
    HE_PMTUD_STATE_SEARCHING = 2,
    /*
     Search complete — effective PMTU is available.
     */
    HE_PMTUD_STATE_SEARCH_COMPLETE = 3,
    /*
     Error during discovery.
     */
    HE_PMTUD_STATE_ERROR = 4,
} he_pmtud_state_t;

/*
 ExpressLane operational state delivered to `he_expresslane_state_change_cb_t`.
 */
typedef enum {
    /*
     ExpressLane not enabled in the config.
     */
    HE_EXPRESSLANE_STATE_DISABLED = 0,
    /*
     Enabled but handshake not yet complete or peer has not enabled it.
     */
    HE_EXPRESSLANE_STATE_INACTIVE = 1,
    /*
     Waiting for the client to respond (server side only).
     */
    HE_EXPRESSLANE_STATE_WAITING_FOR_CLIENT = 2,
    /*
     ExpressLane active — fast path in use.
     */
    HE_EXPRESSLANE_STATE_ACTIVE = 3,
    /*
     Degraded — fell back to normal D/TLS for data packets.
     */
    HE_EXPRESSLANE_STATE_DEGRADED = 4,
} he_expresslane_state_t;

/*
 The negotiated D/TLS protocol version.
 */
typedef enum {
    /*
     Unspecified / not yet negotiated.
     */
    HE_CONNECTION_PROTOCOL_NONE = 0,
    /*
     DTLS 1.2.
     */
    HE_CONNECTION_PROTOCOL_DTLS_1_2 = 1,
    /*
     DTLS 1.3.
     */
    HE_CONNECTION_PROTOCOL_DTLS_1_3 = 2,
    /*
     TLS 1.2.
     */
    HE_CONNECTION_PROTOCOL_TLS_1_2 = 3,
    /*
     TLS 1.3.
     */
    HE_CONNECTION_PROTOCOL_TLS_1_3 = 4,
} he_connection_protocol_t;

/*
 Classification of a raw inbound datagram by `he_conn_identify_packet`,
 derived from the cleartext 16-byte lightway wire header.
 */
typedef enum {
    /*
     Not a valid lightway datagram (too short, or bad magic). Drop it, or
     hand it to `he_conn_outside_data_received` which will also reject it.
     */
    HE_PACKET_KIND_UNDECIDABLE = 0,
    /*
     A DTLS / control datagram (`expresslane_data = 0`). Route the whole
     datagram to `he_conn_outside_data_received`.
     */
    HE_PACKET_KIND_CONTROL = 1,
    /*
     An ExpressLane data datagram (`expresslane_data = 1`). Strip the
     16-byte header and decrypt the remainder with
     `he_expresslane_decrypt`, keyed by the returned `session_id`.
     */
    HE_PACKET_KIND_EXPRESSLANE = 2,
} he_packet_kind_t;

/*
 Packet-padding mode.  Mirrors `he_padding_type` from the OSS C library.
 The Rust `lightway-core` does not currently expose padding control via its
 public API; this enum is provided for source-compatibility with consumers
 that read or pass the value through config structs without calling a setter.
 */
typedef enum {
    /*
     No padding applied.
     */
    HE_PADDING_NONE = 0,
    /*
     Pad every packet to the full MTU.
     */
    HE_PADDING_FULL = 1,
    /*
     Pad packets to 450 bytes.
     */
    HE_PADDING_450 = 2,
} he_padding_type_t;

/*
 Transport type for a Lightway connection.
 */
typedef enum {
    /*
     UDP / DTLS transport.
     */
    HE_CONNECTION_TYPE_DATAGRAM = 0,
    /*
     TCP / TLS transport.
     */
    HE_CONNECTION_TYPE_STREAM = 1,
} he_connection_type_t;

/*
 Top-level handle allocated by `he_client_create()`.

 C callers treat this struct as opaque and interact with it via the accessor
 functions declared in `lightway_cffi.h` (e.g. `he_client_get_conn`,
 `he_client_get_ssl_ctx`).  Concurrent data-path calls (e.g.
 `he_conn_outside_data_received`, `he_conn_inside_packet_received`,
 `he_conn_nudge`) are serialised internally by the library before any
 mutable access to the underlying client state.

 */
typedef struct he_client_t he_client_t;

/*
 Per-connection state embedded inside `he_client_t`.

 Exposed to C via `he_client_get_conn()`; holds credentials and runtime
 state for a single tunnel connection.
 */
typedef struct he_conn_t he_conn_t;

/*
 SSL / protocol context.  Holds per-connection configuration that in the OSS
 C library lives inside `he_ssl_ctx_t`.  C code accesses this via
 `client->ssl_ctx`.
 */
typedef struct he_ssl_ctx_t he_ssl_ctx_t;

/*
 Called whenever the connection state changes.
 */
typedef he_return_code_t (*he_state_change_cb_t)(he_conn_t *conn,
                                                 he_conn_state_t new_state,
                                                 void *context);

/*
 Called when a decrypted inside (TUN) packet is ready to inject.
 */
typedef he_return_code_t (*he_inside_write_cb_t)(he_conn_t *conn,
                                                 uint8_t *packet,
                                                 uintptr_t length,
                                                 void *context);

/*
 Called when an encrypted outside (wire) packet is ready to send.
 */
typedef he_return_code_t (*he_outside_write_cb_t)(he_conn_t *conn,
                                                  uint8_t *packet,
                                                  uintptr_t length,
                                                  void *context);

/*
 IPv4 network configuration delivered by the server via
 `he_network_config_ipv4_cb_t`.

 All string fields are NUL-terminated and at most 64 bytes including the
 terminator (matching the OSS C library layout).
 */
typedef struct {
    /*
     Virtual IP address assigned to this client (dotted-decimal).
     */
    char local_ip[64];
    /*
     DNS server IP (dotted-decimal).
     */
    char dns_ip[64];
    /*
     VPN gateway / peer IP (dotted-decimal).
     */
    char peer_ip[64];
    /*
     Inside MTU for this connection.
     */
    uint16_t mtu;
} he_network_config_ipv4_t;

/*
 Called when the server delivers IPv4 network configuration.
 */
typedef he_return_code_t (*he_network_config_ipv4_cb_t)(he_conn_t *conn,
                                                        he_network_config_ipv4_t *config,
                                                        void *context);

/*
 Called when the server delivers opaque server-config data.
 */
typedef he_return_code_t (*he_server_config_cb_t)(he_conn_t *conn,
                                                  uint8_t *buffer,
                                                  uintptr_t length,
                                                  void *context);

/*
 Called when the keepalive nudge interval changes.
 */
typedef he_return_code_t (*he_nudge_time_cb_t)(he_conn_t *conn, int32_t timeout, void *context);

/*
 Called on miscellaneous connection events.
 */
typedef he_return_code_t (*he_event_cb_t)(he_conn_t *conn, he_conn_event_t event, void *context);

/*
 Called to authenticate a username / password pair (server role).
 */
typedef bool (*he_auth_cb_t)(he_conn_t *conn,
                             const char *username,
                             const char *password,
                             void *context);

/*
 Called to authenticate an opaque auth-token (server role).
 */
typedef bool (*he_auth_token_cb_t)(he_conn_t *conn,
                                   const uint8_t *token,
                                   uintptr_t len,
                                   void *context);

/*
 Called to authenticate via an arbitrary auth buffer (server role).
 */
typedef bool (*he_auth_buf_cb_t)(he_conn_t *conn,
                                 uint8_t auth_type,
                                 uint8_t *buffer,
                                 uint16_t length,
                                 void *context);

/*
 Called to let the server-side app populate the network config.
 */
typedef he_return_code_t (*he_populate_network_config_ipv4_cb_t)(he_conn_t *conn,
                                                                 he_network_config_ipv4_t *config,
                                                                 void *context);

/*
 Called when the PMTUD state changes.
 */
typedef he_return_code_t (*he_pmtud_state_change_cb_t)(he_conn_t *conn,
                                                       he_pmtud_state_t state,
                                                       void *context);

/*
 Called when the PMTUD probe timer fires.
 */
typedef he_return_code_t (*he_pmtud_time_cb_t)(he_conn_t *conn, int32_t timeout, void *context);

/*
 Symmetric keys and session ID delivered to `he_expresslane_cb_t` whenever
 the fast-path key material is refreshed.

 The kernel-mode NDIS driver consumes these to encrypt/decrypt ExpressLane
 data packets without going through the Lightway userspace stack.
 */
typedef struct {
    /*
     Session identifier — 8 bytes, little-endian u64 on the wire.
     */
    uint8_t session_id[8];
    /*
     256-bit AES/ChaCha key for packets **sent** by this endpoint.
     */
    uint8_t self_key[32];
    /*
     256-bit AES/ChaCha key for packets **received** by this endpoint.
     */
    uint8_t peer_key[32];
    /*
     Negotiated ExpressLane wire version (1 = V1, 2 = V2). Selects the AEAD
     AAD layout: a consumer driving `lightway-expresslane-cffi` must pass
     this exact value to `he_expresslane_session_create`, since guessing
     wrong makes every data packet fail authentication.
     */
    uint8_t version;
} he_expresslane_keys_t;

/*
 Called when ExpressLane key material is refreshed.

 `keys` points to a stack-allocated `he_expresslane_keys_t` valid only
 for the duration of the call — copy the contents if you need to retain them.
 */
typedef he_return_code_t (*he_expresslane_cb_t)(he_conn_t *conn,
                                                const he_expresslane_keys_t *keys,
                                                void *context);

/*
 Called when the ExpressLane operational state changes.
 */
typedef he_return_code_t (*he_expresslane_state_change_cb_t)(he_conn_t *conn,
                                                             he_expresslane_state_t state,
                                                             void *context);

/*
 Called by the ExpressLane health monitor to read the offloaded packet
 counters. When the data path is offloaded (encrypt/decrypt via
 `he_expresslane_*` instead of `he_conn_t`), `lightway-core`'s own counters
 stay at zero and healthy traffic looks like 100% loss, degrading the fast
 path — so register this via `he_ssl_ctx_set_expresslane_metrics_cb` to
 report the real counters.

 The callback must write the connection's cumulative ExpressLane packets
 sent/received into `*sent` / `*received` (e.g. from
 `he_expresslane_packets_sent` / `he_expresslane_packets_received` on the
 `he_expresslane_session_t`) and return `HE_SUCCESS`. A non-`HE_SUCCESS`
 return is treated as zero counters.

 IMPORTANT — identify the session by `conn`, NOT by `session_id`. There is one
 offload session per connection, and `conn` is a stable key for it. The
 `session_id` argument is `lightway-core`'s *current* view and is only
 advisory: during a session-id rotation it can briefly lag the id the offload
 has already adopted (core queries metrics while handling a Pong, before it
 applies that packet's rotated id). A callback that looked the session up by
 an exact `session_id` match would miss during the rotation window, return
 zero, and cause a spurious degrade. `session_id` points to 8 bytes valid
 only for the call.
 */
typedef he_return_code_t (*he_expresslane_metrics_cb_t)(he_conn_t *conn,
                                                        const uint8_t *session_id,
                                                        uint64_t *sent,
                                                        uint64_t *received,
                                                        void *context);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Return a NUL-terminated C string identifying the lightway build.

 The returned pointer is valid for the lifetime of the process.
 The caller must not free it.
 */
const char *he_lightway_version(void);

/*
 Return a NUL-terminated C string with the WolfSSL version in use.

 The returned pointer is valid for the lifetime of the process.
 The caller must not free it.
 */
const char *he_wolfssl_version(void);

/*
 Return a static NUL-terminated name for a return code, suitable for logging.

 Takes the raw integer value (not the `he_return_code_t` enum) so that an
 out-of-range value from C is reported as `"HE_ERR_UNKNOWN"` rather than
 being reinterpreted as an invalid enum discriminant (which would be UB).

 # Safety
 Always returns a valid, non-null pointer regardless of the value passed.
 */
const char *he_return_code_name(int code);

/*
 Return a static NUL-terminated name for a connection protocol.

 Takes the raw integer value (not the `he_connection_protocol_t` enum) so an
 out-of-range value from C is reported as `"unknown"` rather than triggering
 UB on an invalid enum discriminant.

 # Safety
 Always returns a valid, non-null pointer.
 */
const char *he_connection_protocol_name(int protocol);

/*
 Initialise the Lightway library.  Must be called once before any other
 `he_*` function.

 # Safety
 Must only be called from a single thread during process initialisation.
 */
he_return_code_t he_init(void);

/*
 Clean up resources allocated by `he_init()`.

 # Safety
 Must be called after all connections have been destroyed.
 */
void he_cleanup(void);

/*
 Allocate a new `he_client_t`.

 Returns a heap-allocated pointer. Aborts on allocation failure.
 The caller must free it with `he_client_destroy`.

 # Safety
 The returned pointer must be freed with `he_client_destroy`.
 */
he_client_t *he_client_create(void);

/*
 Free a `he_client_t` previously allocated by `he_client_create`.

 # Safety
 `client` must be a valid pointer obtained from `he_client_create` and must
 not be used after this call.

 Destruction is **not** internally serialised against other calls: the
 per-client lock cannot protect this because the lock lives *inside* the
 allocation being freed (and the data path reaches it by dereferencing a
 `*mut he_conn_t` that points into the same allocation). The caller MUST
 therefore guarantee that every thread which could call any `he_*` function
 on this client — in particular the data-path calls
 `he_conn_outside_data_received`, `he_conn_inside_packet_received` and
 `he_conn_nudge` — has fully quiesced before calling `he_client_destroy`.
 Calling a data-path function concurrently with (or after) destruction is a
 use-after-free. In particular, `he_client_destroy` must not be called from
 within any callback that runs while the per-client mutex is held (e.g. from
 a state-change callback triggered by `he_client_disconnect`).

 Enforcing this in-library would require a reference-counted handle (so the
 allocation outlives in-flight calls); that is a deliberate future change.
 */
void he_client_destroy(he_client_t *client);

/*
 Return a pointer to the `he_conn_t` embedded inside a `he_client_t`.

 The returned pointer is valid for the lifetime of the client and is stable
 (never moves).  C code can compare it with the `conn` pointer delivered to
 callbacks to identify which tunnel fired the event.

 # Safety
 `client` must be a valid non-null pointer.
 */
he_conn_t *he_client_get_conn(he_client_t *client);

/*
 Return a pointer to the `he_ssl_ctx_t` embedded inside a `he_client_t`.

 # Safety
 `client` must be a valid non-null pointer.
 */
he_ssl_ctx_t *he_client_get_ssl_ctx(he_client_t *client);

/*
 Validate that a client is fully configured and ready to connect.

 # Safety
 `client` must be a valid non-null pointer.
 */
he_return_code_t he_client_is_config_valid(const he_client_t *client);

/*
 Initiate the connection to the Lightway server.

 Builds and starts a `lightway-core` `Connection`, wiring the C callbacks
 to the Rust I/O traits.  The TLS handshake is not yet complete after this
 returns — the caller must pump `he_conn_outside_data_received` and
 `he_conn_nudge` until the state-change callback fires `HE_STATE_ONLINE`.

 # Safety
 `client` must be a valid non-null pointer.
 */
he_return_code_t he_client_connect(he_client_t *client);

/*
 Gracefully disconnect a client.

 # Safety
 `client` must be a valid non-null pointer.
 */
he_return_code_t he_client_disconnect(he_client_t *client);

/*
 Set the connection-state-change callback.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_state_change_cb(he_ssl_ctx_t *ssl_ctx, he_state_change_cb_t cb);

/*
 Set the inside-write (decrypted TUN packet ready) callback.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_inside_write_cb(he_ssl_ctx_t *ssl_ctx, he_inside_write_cb_t cb);

/*
 Set the outside-write (encrypted wire packet ready) callback.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_outside_write_cb(he_ssl_ctx_t *ssl_ctx, he_outside_write_cb_t cb);

/*
 Set the IPv4 network-config callback.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_network_config_ipv4_cb(he_ssl_ctx_t *ssl_ctx,
                                                       he_network_config_ipv4_cb_t cb);

/*
 Set the server-config callback.

 Accepted for source/ABI compatibility, but this shim does not currently
 deliver server-config data, so the callback is stored and never invoked.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_server_config_cb(he_ssl_ctx_t *ssl_ctx, he_server_config_cb_t cb);

/*
 Set the nudge-time callback.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_nudge_time_cb(he_ssl_ctx_t *ssl_ctx, he_nudge_time_cb_t cb);

/*
 Set the connection-event callback.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_event_cb(he_ssl_ctx_t *ssl_ctx, he_event_cb_t cb);

/*
 Set the username/password authentication callback (server role).

 Accepted for source/ABI compatibility with the OSS C library.  This is a
 client-only shim, so the callback is stored but never invoked.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_auth_cb(he_ssl_ctx_t *ssl_ctx, he_auth_cb_t cb);

/*
 Set the auth-token callback (server role).

 Accepted for source/ABI compatibility with the OSS C library.  This is a
 client-only shim, so the callback is stored but never invoked.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_auth_token_cb(he_ssl_ctx_t *ssl_ctx, he_auth_token_cb_t cb);

/*
 Set the auth-buffer callback (server role).

 Accepted for source/ABI compatibility with the OSS C library.  This is a
 client-only shim, so the callback is stored but never invoked.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_auth_buf_cb(he_ssl_ctx_t *ssl_ctx, he_auth_buf_cb_t cb);

/*
 Set the populate-network-config callback (server role).

 Accepted for source/ABI compatibility with the OSS C library.  This is a
 client-only shim, so the callback is stored but never invoked.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_populate_network_config_ipv4_cb(he_ssl_ctx_t *ssl_ctx,
                                                                he_populate_network_config_ipv4_cb_t cb);

/*
 Set the PMTUD state-change callback.

 NOTE: PMTUD is not currently driven by this shim, so this callback is stored
 but never invoked.  Accepted for ABI compatibility; see
 `he_conn_get_effective_pmtu`.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_pmtud_state_change_cb(he_ssl_ctx_t *ssl_ctx,
                                                      he_pmtud_state_change_cb_t cb);

/*
 Set the PMTUD timer callback.

 NOTE: PMTUD is not currently driven by this shim, so this callback is stored
 but never invoked.  Accepted for ABI compatibility.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_pmtud_time_cb(he_ssl_ctx_t *ssl_ctx, he_pmtud_time_cb_t cb);

/*
 Set the CA certificate for server verification.

 `ca_cert` is copied; the caller retains ownership of the buffer.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 `ca_cert` must point to `length` readable bytes.
 */
he_return_code_t he_ssl_ctx_set_ca(he_ssl_ctx_t *ssl_ctx, const uint8_t *ca_cert, uintptr_t length);

/*
 Set the expected server Distinguished Name for certificate checking.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 `server_dn` must be a valid NUL-terminated C string.
 */
he_return_code_t he_ssl_ctx_set_server_dn(he_ssl_ctx_t *ssl_ctx, const char *server_dn);

/*
 Enable or disable post-quantum cryptography.

 When enabled, the client offers a post-quantum key-share group
 (P521MLKEM1024) during the TLS handshake; when disabled, the handshake uses
 the classical key-share groups. The group matches the reference Lightway
 client default and the server's preferred PQC group.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_use_pqc(he_ssl_ctx_t *ssl_ctx, bool use_pqc);

/*
 Enable or disable ChaCha20 cipher preference.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_use_chacha20(he_ssl_ctx_t *ssl_ctx, bool use_chacha20);

/*
 Set the connection transport type (datagram or stream).

 Takes the raw integer value so that an out-of-range value from C is rejected
 with `HE_ERR_BAD_PARAM` rather than stored as an invalid enum discriminant
 (which would be UB when later matched on the data path).

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_connection_type(he_ssl_ctx_t *ssl_ctx, int connection_type);

/*
 Enable the ExpressLane fast-path data plane for this connection.

 Must be called before `he_client_connect`. Only effective on DTLS (datagram)
 connections; silently ignored for TLS (stream) connections.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_enable_expresslane(he_ssl_ctx_t *ssl_ctx, bool enable);

/*
 Register the callback that receives fresh ExpressLane key material.

 Called whenever `lightway-core` completes an ExpressLane key exchange.
 The `he_expresslane_keys_t` passed to the callback is stack-allocated and
 valid only for the duration of the call — copy it if you need to retain it.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_expresslane_cb(he_ssl_ctx_t *ssl_ctx, he_expresslane_cb_t cb);

/*
 Register the callback for ExpressLane operational-state changes.

 Fired with `HE_EXPRESSLANE_STATE_ACTIVE` once the fast path is fully
 established, and with `HE_EXPRESSLANE_STATE_DEGRADED` or
 `HE_EXPRESSLANE_STATE_INACTIVE` if it later falls back.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_expresslane_state_change_cb(he_ssl_ctx_t *ssl_ctx,
                                                            he_expresslane_state_change_cb_t cb);

/*
 Register the callback that supplies offloaded ExpressLane packet counters
 to the health monitor.

 Install this whenever the ExpressLane data path is offloaded (decrypt/encrypt
 via `he_expresslane_decrypt`/`he_expresslane_encrypt` instead of
 `he_conn_outside_data_received`/`he_conn_inside_packet_received`). Without it,
 `lightway-core`'s own packet counters stay at zero while the peer reports the
 real numbers, so the health monitor sees ~100% loss and degrades the fast
 path back to D/TLS. See `he_expresslane_metrics_cb_t`.

 # Safety
 `ssl_ctx` must be a valid non-null pointer.
 */
he_return_code_t he_ssl_ctx_set_expresslane_metrics_cb(he_ssl_ctx_t *ssl_ctx,
                                                       he_expresslane_metrics_cb_t cb);

/*
 Set the username for password-based authentication.

 # Safety
 `conn` must be a valid non-null pointer.
 `username` must be a valid NUL-terminated C string.
 */
he_return_code_t he_conn_set_username(he_conn_t *conn, const char *username);

/*
 Set the password for password-based authentication.

 # Safety
 `conn` must be a valid non-null pointer.
 `password` must be a valid NUL-terminated C string.
 */
he_return_code_t he_conn_set_password(he_conn_t *conn, const char *password);

/*
 Set an opaque auth token.

 `token` is copied; the caller retains ownership of the buffer.

 # Safety
 `conn` must be a valid non-null pointer.
 `token` must point to `length` readable bytes.
 */
he_return_code_t he_conn_set_auth_token(he_conn_t *conn, const uint8_t *token, uintptr_t length);

/*
 Set the SNI hostname for TLS server-name indication.

 # Safety
 `conn` must be a valid non-null pointer.
 `hostname` must be a valid NUL-terminated C string.
 */
he_return_code_t he_conn_set_sni_hostname(he_conn_t *conn, const char *hostname);

/*
 Set the outside (wire) MTU.

 # Safety
 `conn` must be a valid non-null pointer.
 */
he_return_code_t he_conn_set_outside_mtu(he_conn_t *conn, uint16_t mtu);

/*
 Store an opaque context pointer that is passed back to all callbacks.

 # Safety
 `conn` must be a valid non-null pointer.
 `context` lifetime is the caller's responsibility.
 */
he_return_code_t he_conn_set_context(he_conn_t *conn, void *context);

/*
 Get the current keepalive nudge interval in milliseconds.

 Returns 0 if `conn` is null.

 # Safety
 `conn` must be a valid non-null pointer or null.
 */
int32_t he_conn_get_nudge_time(const he_conn_t *conn);

/*
 Get the negotiated outside MTU.

 # Safety
 `conn` must be a valid non-null pointer.
 */
uint16_t he_conn_get_outside_mtu(const he_conn_t *conn);

/*
 Get the effective path MTU determined by PMTUD.

 NOTE: this shim does not currently drive Path MTU Discovery (the pinned
 `lightway-core` requires a PMTUD timer that is not wired here, and exposes no
 effective-MTU accessor), so this always returns 0.  Retained for ABI
 compatibility; treat 0 as "PMTUD not available".

 # Safety
 `conn` must be a valid non-null pointer or null.
 */
uint16_t he_conn_get_effective_pmtu(const he_conn_t *conn);

/*
 Get the negotiated connection protocol.

 # Safety
 `conn` must be a valid non-null pointer.
 */
he_connection_protocol_t he_conn_get_current_protocol(const he_conn_t *conn);

/*
 Get the negotiated cipher suite name, or null if not yet negotiated.

 The value is captured once when the handshake exposes it and is then stable
 for the connection's lifetime, so the returned pointer remains valid. This
 getter takes no lock (and so is safe to call from a callback), but for that
 reason it should be read after the `HE_STATE_ONLINE` transition, by which
 point the value is fixed.

 # Safety
 `conn` must be a valid non-null pointer or null.
 */
const char *he_conn_get_cipher_name(const he_conn_t *conn);

/*
 Get the TLS curve name, or null if not yet negotiated.

 As with `he_conn_get_cipher_name`, the value is captured once and stable for
 the connection's lifetime; read it after `HE_STATE_ONLINE`.

 # Safety
 `conn` must be a valid non-null pointer or null.
 */
const char *he_conn_get_curve_name(const he_conn_t *conn);

/*
 Get the current session ID as a little-endian `uint64_t`.

 Returns `0` if no connection is active yet, if `client` is null, or if
 called re-entrantly from within a callback that already holds the lock.

 # Safety
 `client` must be null or a valid pointer from `he_client_create`.
 */
uint64_t he_conn_get_session_id(const he_client_t *client);

/*
 Classify a raw inbound datagram by its cleartext 16-byte lightway wire
 header, without any connection state or decryption.

 This is the demux for an ExpressLane data-plane offload: an
 `HE_PACKET_KIND_EXPRESSLANE` datagram can be decrypted directly with
 `he_expresslane_decrypt` after stripping the returned `*header_len` bytes
 (keyed by the returned `session_id`), while an `HE_PACKET_KIND_CONTROL`
 datagram must be handed unchanged to `he_conn_outside_data_received`.

 Classification is a pure function of the datagram bytes and delegates to
 `lightway-core`'s own header parser, so it stays correct across wire-format
 changes. It does NOT run any outside/obfuscation plugins, so it is only
 valid when no such plugin is configured (this shim configures none).

 On success `*kind` is always written. For `CONTROL`/`EXPRESSLANE`,
 `session_id` (if non-null) receives the 8-byte session id and `*header_len`
 (if non-null) receives the header size (16). A datagram that is not a valid
 lightway frame yields `HE_PACKET_KIND_UNDECIDABLE` and still returns
 `HE_SUCCESS` — classification succeeded; the packet simply isn't ours.

 # Safety
 `packet` must point to `len` readable bytes (may be null iff `len == 0`).
 `kind` must be a valid non-null pointer. `session_id`, if non-null, must be
 writable for 8 bytes. `header_len`, if non-null, must be writable.
 */
he_return_code_t he_conn_identify_packet(const uint8_t *packet,
                                         uintptr_t len,
                                         he_packet_kind_t *kind,
                                         uint8_t *session_id,
                                         uintptr_t *header_len);

/*
 Build the 16-byte cleartext lightway wire header to prepend to an
 ExpressLane data datagram produced by `he_expresslane_encrypt`. The header
 carries the connection's protocol version (fixed for a client), the
 caller-supplied `session_id`, `expresslane_data = 1`, and
 `aggressive_mode = 0`.

 # Why the caller supplies `session_id`
 The offload diverts inbound ExpressLane datagrams straight to
 `he_expresslane_decrypt`, so `lightway-core` never observes their outer
 header. If the server rotates the session id and the echo arrives only on
 ExpressLane traffic, the connection's own `session_id()` lags behind — using
 it here would keep emitting the stale id and the rotation would never
 complete. The offload is the authority for the ExpressLane session id, so it
 passes the current one: initially the id from the `he_expresslane_cb_t` key
 callback, then updated whenever an inbound ExpressLane datagram's header
 (via `he_conn_identify_packet`) carries a different, successfully-decrypted
 session id. (Adopt a new id only AFTER `he_expresslane_decrypt` succeeds, so
 a forged header cannot steer egress.) The DTLS control channel converges
 independently — the server tolerates a transient session-id mismatch on
 control packets — so this only governs the ExpressLane egress framing.

 Returns:
 - `HE_ERR_NULL_POINTER` if `out`, `session_id`, or `client` is null.
 - `HE_ERR_BAD_PARAM` if `session_id` is the reserved all-zero / rejected
   sentinel (a header carrying it is unroutable).
 - `HE_ERR_INVALID_CONN_STATE` if no connection is active yet, or if called
   re-entrantly from within a callback that already holds the per-client lock.

 # Safety
 `client` must be null or a valid pointer from `he_client_create`.
 `session_id` must point to 8 readable bytes. `out` must be writable for 16
 bytes.
 */
he_return_code_t he_conn_build_expresslane_header(const he_client_t *client,
                                                  const uint8_t *session_id,
                                                  uint8_t *out);

/*
 Rotate the ExpressLane send key if the rotation interval has elapsed.

 `lightway-core` normally rotates the ExpressLane key off the back of
 outbound *inside* traffic (`Connection::inside_data_received`) and off an
 inbound peer `ExpresslaneConfig`. A data-plane offload bypasses
 `he_conn_inside_packet_received` for every ExpressLane packet, so on a
 long-lived, effectively one-directional offloaded egress flow neither
 trigger fires and the send key is never rotated past its interval. The
 always-on nudge/keepalive tick does not rotate either.

 Call this once per nudge cycle (next to `he_conn_nudge`) to restore the
 interval-bounded rotation. It is internally gated by the connection's
 `time_to_rotate_key()` check, so it is a cheap no-op until the interval
 elapses and only rotates — sending a single `ExpresslaneConfig` frame —
 when actually due. A `degraded`/`not-supported` connection is treated as
 "nothing to rotate" and reported as success.

 Returns `HE_ERR_NULL_POINTER` for a null `conn`, `HE_ERR_INVALID_CONN_STATE`
 if no connection is active yet, and `HE_SUCCESS` otherwise.

 # Safety
 `conn` must be null or a valid pointer to a `he_conn_t` whose `client_ptr`
 back-pointer was set by `he_client_t::new()` and has not been freed. Do not
 call re-entrantly from within a callback that already holds the per-client
 lock.
 */
he_return_code_t he_conn_expresslane_rotate_if_due(he_conn_t *conn);

/*
 Feed an encrypted packet received from the wire into the connection.

 The decrypted inner payload will be returned via `inside_write_cb`.

 # Safety
 `conn` and `buffer` must be valid non-null pointers.
 `buffer` must point to `length` readable bytes.
 */
he_return_code_t he_conn_outside_data_received(he_conn_t *conn, uint8_t *buffer, uintptr_t length);

/*
 Feed a plaintext inner packet into the connection for encryption and
 transmission to the server.

 The encrypted payload will be returned via `outside_write_cb`.

 # Safety
 `conn` and `packet` must be valid non-null pointers.
 `packet` must point to `length` readable bytes.
 */
he_return_code_t he_conn_inside_packet_received(he_conn_t *conn, uint8_t *packet, uintptr_t length);

/*
 Nudge the connection — retransmit handshake messages if the keepalive
 timer has expired.

 # Safety
 `conn` must be a valid non-null pointer.
 */
he_return_code_t he_conn_nudge(he_conn_t *conn);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* XV_LIGHTWAY_CFFI_H */

/* Source-compatibility alias: OSS he.h typedef'd the enum tag as both
 * `he_connection_type` and `he_connection_type_t`. Provide the untagged
 * alias so existing structs using `he_connection_type` as a type still compile.
 * Must appear AFTER he_connection_type_t is defined above. */
typedef he_connection_type_t he_connection_type;
